// css
import './EvenFibonacciNumbers.css';

// react
import { useEffect, useState } from 'react';

// component
import { Challange } from '../../../components/challange/Challange';

// external
import DOMPurify from 'dompurify';

export const EvenFibonacciNumbers = () => {
    const [description, setDescription] = useState('');

    useEffect(() => {
        setDescription(DOMPurify.sanitize('Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with <b>1</b> and <b>2</b>, the first terms <b>10</b> will be:. \
            <br/><br/><center><b>1</b>,<b>2</b>,<b>3</b>,<b>8</b>,<b>13</b>,<b>21</b>,<b>34</b>,<b>55</b>,<b>89</b>,...</center> <br/><br/> \
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'));
    }, [])

    const code = () => {
        return `
        const answer = () => {
            let sum = 0;
            for (let i = 0; i < 1000; i++) {
                if (i % 3 === 0 || i % 5 === 0) {
                    sum += i;
                }
            }
            return sum;
        }`;
    }

    const answer = () => {
        let sum = 0;
        for (let i = 0; i < 1000; i++) {
            if (i % 3 === 0 || i % 5 === 0) {
                sum += i;
            }
        }
        return sum;
    }

    return (<>
        <div className='even_fibonacci_numbers'>
            <Challange description={description} code={code()} answer={answer()}/>
        </div>
    </>);
}